### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by arghadipmanna101** [Sayan67/Youtube-uploader#1] opened 2024-01-16 12:57 UTC
- will add gif
- will stylize the readme
- will update how to contribute
- Will update contributors name in Readme file.

**Comment by arghadipmanna101** [comment] 2024-01-16 12:57
please assign me under Apertre

**Comment by Sayan67** [comment] 2024-01-16 13:33
Finish it by tomorrow. PR will be accepted only if the changes are valid and necessary. Unnecessary small changes will not be accepted.

**Comment by arghadipmanna101** [comment] 2024-01-16 13:46
ok.

**Comment by arghadipmanna101** [comment] 2024-01-17 06:49
how can i run the application?
I want to add some preview images

**Comment by Sayan67** [comment] 2024-01-18 05:17
> how can i run the application? I want to add some preview images

As per the issue is suggesting you don't need to run the application though, still if you want to run the application there is a section in the Readme.md called "How to run locally". Follow that section.

You should have COMPLETE it by yesterday. I am extending the date to today, so hurry up🚀. Otherwise I have to close the issue.

**Closed as completed** 2024-01-19 10:18 UTC
Labels: apertre, easy
